### ISSUE TITLE
70% build complete in JEKYLL 

### ISSUE THREAD

**Issue by manishmarahatta** [foss-np/sfd-2016#2]
converting sfd-2016 page into jekyll , will complete soon

**Comment by amitness** [comment]
Great.

**Comment by mrtordoide** [comment]
Please, complete the 30% before 4:00 PM. Can you do that?

**Comment by mrtordoide** [comment]
@manishmarahatta Where are you?

**Comment by amitness** [comment]
@manishmarahatta Can you share us the progress? If you're stuck, please tell us the details and maybe paste the error message you're getting.
