### ISSUE TITLE
Discuss!

### ISSUE THREAD

**Issue by mrtordoide** [foss-np/sfd-2016#3]
Okay guys! Let's first clear out all those "creator related but not to us" comments as soon as we get it! @studenton

**Comment by mrtordoide** [comment]
And @manishmarahatta I wanted you to some task. Lets try adding the changing text of like openosk.github.io

**Comment by manishmarahatta** [comment]
sure buddy ..on it!!

**Comment by manishmarahatta** [comment]
@mr-turdoide lets not make nav transparent .......3 scroll down it looks horrible

**Comment by manishmarahatta** [comment]
@mr-turdoide  2016 nepal lai pachadi rakham hola ....that don't make any sense .....agadi cha

**Comment by manishmarahatta** [comment]
@mr-turdoide  fixed logo and tag issue

**Comment by manishmarahatta** [comment]
i'll work on transparency and font ...u better work on padding for "2016 Nepal"

**Comment by nikeshbalami** [comment]
Rather than using our photo lets us the wallpaper from SFD Global website of Freedom Matters or Register.

**Comment by mrtordoide** [comment]
Sure @manishmarahatta  and @nikeshbalami

**Comment by mrtordoide** [comment]
@manishmarahatta  Just kept that 2016 Nepal in random. Will work on it

**Comment by mrtordoide** [comment]
And wait @manishmarahatta @nikeshbalami @studenton , Some files are still to upload. :) That's why the nav bar is transparent. Just wait for some while.

**Comment by manishmarahatta** [comment]
okay....i'm working on sfd countdown almost complete ......we could replace the 17th sep stuff

**Comment by mr-turdoide** [comment]
yeah thats the spirit!! Will be awesome.

**Comment by mrtordoide** [comment]
I'll be reuploading the files soon. Just because an error occured.

**Comment by mrtordoide** [comment]
Re-upload completed and now, everything works well. @manishmarahatta Dai,  _sites was not needed. So, it wasn't that confusing this time to upload all. @nikeshbalami Keep suggesting what should be where!

**Comment by mrtordoide** [comment]
@manishmarahatta Are you making that time countdown ?

**Comment by nikeshbalami** [comment]
Lets add some more pages:
- About
- Agenda
        -  Program Draft
        - Expected Session
- Support
        - Sponsor a Event
        - Become a Speaker
- Team
- Celebrating Partners
- Contact

**Comment by mrtordoide** [comment]
Tyo Agenda - Program Draft - Expected Session bhaneko "Agenda" page bhitra ko Program Draft ra Expected Session haru contents haina?

**Comment by mrtordoide** [comment]
@studenton Okay, the nav bar issue is fixed. My fault. I left my modification on half way so it happened! :D

**Comment by amitness** [comment]
So do we have photos of every volunteer now?

**Comment by manishmarahatta** [comment]
guys i'm completely free today ..let us complete this website and get done with it ..maybe lot's of stuff might be pending with this website @mr-turdoide @studenton

**Comment by amitness** [comment]
"Become a Sponsor" ra "Become a Speaker" ko lagi chuttei page banaune ki tei front page ma hunxa form?

**Comment by mrtordoide** [comment]
@studenton No, we donot have!
I have the photos of:
Nikesh Dai, Abhishek Pandey, Rumi Rajbhandari and myself.

I am asking for others to create of their own. So, currently, I removed all photos from the home!

**Comment by mrtordoide** [comment]
@manishmarahatta @studenton Yeah dai, have you made that countdown?

**Comment by mrtordoide** [comment]
@studenton Hunchha tei frontpage mai banauda!! Lets not try making more pages! Will look good!

**Comment by nikeshbalami** [comment]
Guys lets make the page for "Become a Sponsor" and "Become a Speaker" ASAP, we should start sharing it for the sponsorship.

**Comment by amitness** [comment]
@mr-turdoide Official countdown ni ayexa. Tyo use garda ni hunxa. http://softwarefreedomday.org/index.php/promote/countdown

**Comment by manishmarahatta** [comment]
@mr-turdoide @studenton @nikeshbalami guys i really suck at UI tei pani tyo orange color chai alli thik lagena aafno aafno tarka rakham ta......alli flashy bhayo ..i think we need more professional type color (sound's ridiculous) tara alli bold type ko color use garne ki?

**Comment by mrtordoide** [comment]
@manishmarahatta @studenton @nikeshbalami Then lets give a try to the background color of this pic. This looks good! https://drive.google.com/file/d/0B-YGC_yC0qvvVndfbmpvdjRZVmc/view

**Comment by manishmarahatta** [comment]
@mr-turdoide @studenton @nikeshbalami yup this looks great tara alli opacity milayera halam hai

**Comment by mrtordoide** [comment]
@manishmarahatta @nikeshbalami @studenton  Orange thikai thyo huna ta! Bharkhar SFD ko wiki update gardai thiye. That's too orange dominant! :D http://wiki.softwarefreedomday.org/2016/Nepal?highlight=(\bCategoryCountry2016\b)

**Comment by mrtordoide** [comment]
@manishmarahatta @nikeshbalami @studenton Could we possibly use google forms for "Become a sponsor" and "Become a speaker"?

**Comment by mrtordoide** [comment]
I just created main.html for "The Event". To contain "Agenda - Program Draft - Expected Session" and all other details related to the event day!

**Comment by amitness** [comment]
Brown color garda yesto vo

![screenshot from 2016-08-20 22 47 36](https://cloud.githubusercontent.com/assets/8587189/17832672/355148c8-6728-11e6-8e1f-7afbba8e8af3.png)
![screenshot from 2016-08-20 22 47 40](https://cloud.githubusercontent.com/assets/8587189/17832673/3555ff9e-6728-11e6-9598-3b637ba515c0.png)
![screenshot from 2016-08-20 22 47 43](https://cloud.githubusercontent.com/assets/8587189/17832674/355cdc42-6728-11e6-8389-57104d452278.png)

**Comment by amitness** [comment]
Yo vanda orange nei thik lagyo. Yesma ramro color haru xa http://flatuicolors.com .

**Comment by mrtordoide** [comment]
I think orange is okay!

**Comment by nikeshbalami** [comment]
@mr-turdoide we don't need those Google forms kinds of stuff, all we need is a separate static page for both of them, "Become a Sponsor" and "Become a Presenter"

**Comment by amitness** [comment]
@nikeshbalami Tyo page ma form rakhne ho ki sponsorship ko bare lekhne?

Btw, google form rakhena vane aru mildaina. Github ma backend hunna, so afnei form handle garna mildaina. Baru, google form lai page mei embed garna milxa.

**Comment by amitness** [comment]
@mr-turdoide Vai, yo herata if you're free. Google forms lai custom design garne. Kam garxa ki. http://www.earlybirdstrategy.com/customize-google-forms/ . Mero exam xa 2 din. I'll be absent here.

**Comment by mrtordoide** [comment]
@studenton @manishmarahatta @nikeshbalami However, we can create our own but seems to be complicated. https://coderwall.com/p/8lq1ba/how-to-create-a-contact-form-for-a-github-pages-served-jekyll-website

**Comment by nikeshbalami** [comment]
@studenton @mr-turdoide @manishmarahatta Tyo dubai page ma lekhne martai ho, form haru pardena..tyo Drive a vayako Presenter Call and Sponsorship Proposal ko sabai kura haru rakhne natrai ho..so, that sabai lai online pani padna milos vanee ho..form pardena

**Comment by mrtordoide** [comment]
okay @nikeshbalami

**Comment by mrtordoide** [comment]
@nikeshbalami What are we going to include in 'Agenda', 'Program Draft' and 'Expected session'??

**Comment by manishmarahatta** [comment]
@mr-turdoide @nikeshbalami form na parne bhaye pachi ma form ma kaam garna chod diye hai...yedi form chaiene ho bhane pani it's not that complicated garna sakincha...just let me know

**Comment by amitness** [comment]
@mr-turdoide Tyo Moods Restaurant fixed ho? Website ma venue update garna lako.

**Comment by manishmarahatta** [comment]
@studenton ahh moods lounge, tripureshwar fix ho

**Comment by mrtordoide** [comment]
@studenton I am now working on the https://foss-np.github.io/sfd-2016/sfdteam.html page! Lets finish it by tomorrow. On this page, lets make different sections of the volunteers on the basis of Teams section on this page: http://wiki.fossnepal.org/index.php?title=30th_July_2016,_1st_meeting,_Jyaasa,_Lalitpur where the style is same of the volunteers display at home page!

**Comment by mrtordoide** [comment]
@studenton Exams over ? You coming to Kathford today ?

**Comment by amitness** [comment]
Nope, board exams are starting from this Monday. It will be for 28 days.

Ok, I'll work on that.

**Comment by amitness** [comment]
@mr-turdoide I've added all the sections and updated up to design and event documentation team till now. I'll update others in next break. Leave this task to me. You focus on other.

**Comment by amitness** [comment]
@mr-turdoide  I'll complete it by tomorrow noon.

**Comment by studenton** [comment]
@mr-turdoide Ok the work is completed. 

Euta issue xa. Please look into it. Tyo https://foss-np.github.io/sfd-2016/sfdteam.html page ma logistics team ko layout kina ho mili ra xaina 5 jana bhayera. Aru sabei team ko milya xa.

**Comment by amitness** [comment]
@mr-turdoide Ok the work is completed.
