### ISSUE TITLE
Google Fonts Not Loaded by Browser

### ISSUE THREAD

**Issue by amitness** [foss-np/sfd-2016#4]
Site is hosted on github over HTTPS. Looks like chrome is blocking requests to HTTP Resources from our site. Same error in Opera as well.

Here's an excerpt of the error.

```
foss-np.github.io/:18 Mixed Content: The page at 'https://foss-np.github.io/sfd-2016/' was loaded over HTTPS, but requested an insecure stylesheet 'http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800'. This content should also be served over HTTPS.
foss-np.github.io/:19 Mixed Content: The page at 'https://foss-np.github.io/sfd-2016/' was loaded over HTTPS, but requested an insecure stylesheet 'http://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic'. This content should also be served over HTTPS.
```

Figuring out how to solve it.

**Comment by amitness** [comment]
Solved #4. Thanks to SO: http://stackoverflow.com/questions/18026809/google-web-fonts-on-https-pages-on-chrome

**Comment by xecutioner** [comment]
Just use secure http for the stylesheet as well ?
https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic%27 <https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic'>

**Comment by amitness** [comment]
@xecutioner Yes that would work too. Removing the protocol from http://fonts.google... to //fonts.google...
fixed it.
